### ISSUE TITLE
pip package misses astkit dependency

### ISSUE THREAD

**Issue by twirrim** [kevinconway/pycc#10]
I haven't spent much time digging in to wheels etc, but the pycc wheel seems to be missing the dependency on astkit etc that are in the requirements.txt file.

In a fresh python2 virtualenv:
```
$ pip install pycc
Collecting pycc
  Downloading https://files.pythonhosted.org/packages/87/4a/d1f0e2ac05766aeb33f4d29668d997279da06b674fe056aa7876d2bd8318/pycc-2.0.0.tar.gz
Building wheels for collected packages: pycc
  Running setup.py bdist_wheel for pycc ... done
  Stored in directory: /home/paul/.cache/pip/wheels/51/7b/f9/395e8a849c19068c65c30d78df58ebb4ef32e06b19b5bd85e3
Successfully built pycc
Installing collected packages: pycc
Successfully installed pycc-2.0.0
]$ pycc-transform
Traceback (most recent call last):
....
    from astkit.render import SourceCodeRenderer
ImportError: No module named astkit.render

```

Installing astkit then allows pycc-transform to run.

**Comment by kevinconway** [comment]
The root of the problem appears to be that `setuptools` no longer respects (and maybe never did respect) the `requires` kwarg that is specified for `distutils`. The correct field is `install_requires`. Since the automated tests install dependencies using the requirements.txt, it's possible the package has always been invalid.

It's hard to tell, sometimes, why older packages don't work. For example, I recently had an incident where I tried to rebuild an old `npm` package and it ended up producing an invalid build from the same configuration used to create a valid build four years prior. The root cause ended up being that `npm` had multiple, major version changes since then and one of them changed the way it interpreted relative paths...

In any case, I think the right thing to do would be to modify the `setup.py` to use `install_requires`, give the package a minor version bump, and build an actual wheel for PyPI instead of the old source distributions. If that's something you'd like to help with, I'd happily accept the PR and help get the build onto PyPI.
